export const REQUEST_DEDUPLICATION_MODULE_OPTIONS = 'REQUEST_DEDUPLICATION_MODULE_OPTIONS';
export const REQUEST_DEDUPLICATION_INTERCEPTOR = 'REQUEST_DEDUPLICATION_INTERCEPTOR';
export const SKIP_DEDUPLICATE_REQUEST_KEY = 'skipDeduplicateRequest';
