name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'docs/**'

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint check
        run: npm run lint

      - name: Run tests
        run: npm run test:cov

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
