name: SonarCloud Analysis

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - 'docs/**'
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    environment: Quality check
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test and coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
